server:
  port: 8081
mockserver:
  base-url: "http://localhost:${server.port}/${spring.application.name}"

oauth-mock-data:
  clients:
    - client-id: "jme-jwe-ui"
      context: "USER"
      registered-redirect-uri: [ "http://localhost:8080/jme-jwe-scs/",
                                 "http://localhost:4200/" ]
      userroles: [ "jme_@person_#read", "jme_@person_#write" ]

    - client-id: "jme-jwe-it-client"
      client-secret: "{noop}secret"
      context: "SYS"
      userroles: [ "jme_@person_#read", "jme_@person_#write" ]
